name: CI

on:
  push:
    branches: 
      - dev
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    services:
      dbtest:
        image: postgres
        env:
            POSTGRES_PASSWORD: pumaadmin
            POSTGRES_USER: pumaadmin
            POSTGRES_DB: puma
            DATABASE_URL: "postgres://pumaadmin:pumaadmin@dbtest:5432/puma"
        ports:
            - "5432:5432"
    env:
      DB_URL: "postgres://pumaadmin:pumaadmin@dbtest:5432/puma"

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Run npm install
      run: npm install
    
    - name: Test and Coverage
      run: npm run test-coverage

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    #- name: Coveralls
    #  uses: coverallsapp/github-action@master
    #  with:
    #    github-token: ${{ secrets.REPO_TOKEN }}